# Generated by Django 3.0.6 on 2020-07-12 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20200710_1833'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='chead2',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='head2',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='about',
            field=models.CharField(default='Add something about post', max_length=500, verbose_name='About post'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='chead0',
            field=models.CharField(max_length=5000, verbose_name='Content of header'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='chead1',
            field=models.TextField(verbose_name='Content of sub header'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='head0',
            field=models.CharField(max_length=200, verbose_name='Header'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='head1',
            field=models.CharField(max_length=500, verbose_name=' Sub header'),
        ),
    ]
